DROP TABLE IF EXISTS REQUESTS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS SHOPPINGCART;
DROP TABLE IF EXISTS STUFFEDANIMALSTORE;

CREATE TABLE STUFFEDANIMALSTORE (
    StuffieID VARCHAR(64) NOT NULL,
    ProductName VARCHAR(64) NOT NULL,
    ProductSize ENUM('S','M','L','XL') NOT NULL,
    Color VARCHAR(32) NOT NULL,
    Price DECIMAL(6,2) NOT NULL,
    InvQty INT NOT NULL,
    ProductDescription TEXT NOT NULL,
    PRIMARY KEY (StuffieID)
);

CREATE TABLE SHOPPINGCART (
    TrackingID VARCHAR(128) NOT NULL,
    StuffieID VARCHAR(64) NOT NULL,
    CartQty INT NOT NULL,
    PRIMARY KEY (TrackingID, StuffieID),
    FOREIGN KEY (StuffieID) REFERENCES STUFFEDANIMALSTORE(StuffieID) ON DELETE CASCADE
);

CREATE TABLE ORDERS (
    TrackingID VARCHAR(64) NOT NULL,
    OrderStatus VARCHAR(32) NOT NULL,
    Total DECIMAL(10,2) NOT NULL,
    CCInfo VARCHAR(20) NOT NULL,
    ShippingAddr VARCHAR(128) NOT NULL,
    BillingAddr VARCHAR(128) NOT NULL,
    PRIMARY KEY (TrackingID),
    FOREIGN KEY (TrackingID) REFERENCES SHOPPINGCART(TrackingID) ON DELETE CASCADE
);

CREATE TABLE REQUESTS (
    TrackingID VARCHAR(64) NOT NULL,
    StuffieID VARCHAR(64) NOT NULL,
    OrderQty INT NOT NULL,
    PRIMARY KEY (TrackingID, StuffieID),
    FOREIGN KEY (TrackingID) REFERENCES ORDERS(TrackingID) ON DELETE CASCADE,
    FOREIGN KEY (StuffieID) REFERENCES STUFFEDANIMALSTORE(StuffieID) ON DELETE CASCADE
);
